# vi:ft=toml:
#
# See more keys and their definitions at
#   https://doc.rust-lang.org/cargo/reference/manifest.html


[package]
name = "magnetite"
version = "UNKNOWN"
edition = "2021"
default-run = "knock"

[[bin]]
name = "magnetite"
path = "src/magnetite.rs"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

[dependencies]
# clap recommends "~3.2.8" ... which means what now??
#   https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
#     3.2.8 means 3.2.8 <= v < 4.0.0
#     ^3.2.8 means 3.2.8
#     ~3.2.8 means 3.2.8 <= v < 3.3.0

#clap = { version = "3.2.8", features = [ "cargo" ] }
#syslog = "^6.0"
#log = { version = "0.4.17", features = [ "std" ] }
#env_logger = "0.8.4"
#tokio = { version="1.20.1", features=["full"] }
#dirs = "4.0"
#config = "0.13.2"

[dependencies.pyo3]
version = "0.17.3"
features = ["auto-initialize"]
